### PR TITLE
Text-based file for translations, and autogeneration of .js locale files

### PR DESCRIPTION
**Pull request by rcassani**
Having a text-based CSV (rather the binary .ods) file for the translation will make easier the tracking, editing and merging of that file in the future. I added also a python script to generate the .js files from the translation CSV file

### CODE REVIEW

**Comment by jdpigeon** [comment]
Have you tested whether the .js files generated by your py script play well with the rest of the app?

**Comment by rcassani** [comment]
In terms of content, there are *keys* in the `/i18n/locales` files that are not present in the translation file, keys related to the BCI part. I'll add all those additional keys to the table. Then we can test how the auto-generated `.js` behave

**Comment by rcassani** [comment]
The translation CSV file was updated to take into account new labels. I'm having some issues installing watchman to be able to deploy the app here. Can someone compile and run the app using the autogenrated `.js` files?

**Comment by jdpigeon** [comment]
I can take care of that

**Pull request merged**
