### PR TITLE
Update generate_locales.py

### PR DESCRIPTION
**Pull request by rcassani**
Missing `;` at closing `export default {}`

### CODE REVIEW

**Comment by rcassani** [comment]
Just detected a `;` was missing in the Python script

**Comment by jdpigeon** [comment]
It works! With some small tweaks to the text csv, I've got the generated files working in the app

**Comment by rcassani** [comment]
What kind of tweaks? Something that need to be repaired for the other languages?

**Comment by jdpigeon** [comment]
I added some new lines and removed some old ones, mostly in slide-end. The version you were working with must have been a little bit outdated

All the variable names are correct and the text lines up correctly. However, translators should make sure to take a look at the en.js file rather than just the suffix-ed test in the fr and es files. I assumed those were placeholders and didn't  bother updating them as scrupulously

**Comment by rcassani** [comment]
Cool!
Yes, for now the ES and FR columns are for demonstration. The idea is that future translators copy the first (eng) column and from generate the translation from it

**Pull request merged**
